d <- read.table("test_data_files/swissmetro/swissmetro.dat", header = TRUE)
cat("rows:", nrow(d), "cols:", ncol(d), "\n")
cat("IDs:", length(unique(d$ID)), "\n")
cat("Tasks per ID:", paste(range(table(d$ID)), collapse = "-"), "\n")
cat("CHOICE:\n"); print(table(d$CHOICE, useNA = "always"))
cat("SP only?\n"); print(table(d$SP))
cat("availability counts:\n")
for (a in c("TRAIN_AV", "SM_AV", "CAR_AV")) cat(sprintf("  %s = 1 in %d\n", a, sum(d[[a]] == 1)))
cat("All three avail:", sum(d$TRAIN_AV == 1 & d$SM_AV == 1 & d$CAR_AV == 1), "\n")
cat("CHOICE = 0 (missing/non-response):", sum(d$CHOICE == 0), "\n")
d2 <- d[d$CHOICE != 0 & d$TRAIN_AV == 1 & d$SM_AV == 1 & d$CAR_AV == 1, ]
cat("Filtered: rows =", nrow(d2), ", IDs =", length(unique(d2$ID)), "\n")
cat("Filtered tasks/ID range:", paste(range(table(d2$ID)), collapse = "-"), "\n")
cat("Filtered choice distribution:\n"); print(table(d2$CHOICE))
cat("Attribute summaries (train/SM/car time, cost):\n")
print(summary(d2[, c("TRAIN_TT", "TRAIN_CO", "SM_TT", "SM_CO", "SM_HE", "CAR_TT", "CAR_CO")]))
