options(empirical.skip = TRUE)
source("R/empirical_application.R")
db <- load_empirical_database()
cat("N respondents:", length(unique(db$ID)), "\n")
cat("T tasks per resp:", max(db$TASK), "\n")
cat("Total rows:", nrow(db), "\n")
cat("\nChoice distribution:\n"); print(table(db$CHOICE))
cat("\nFirst respondent (ID=1) all 8 tasks:\n")
print(db[db$ID == 1, c("ID","TASK","CHOICE","x1_2","x1_3","x7_2","x7_3","price_2","price_3")])
cat("\nAlt 1 (status quo) all-zero check across policy attrs (should all be 0):\n")
sq_cols <- c("x1_1","x2_1","x3_1","x4_1","x5_1","x6_1","x7_1","x8_1","price_1")
print(sapply(db[, sq_cols], function(x) sum(x != 0)))
cat("\nNon-zero counts for alt 2 attrs (should be > 0):\n")
a2_cols <- c("x1_2","x2_2","x3_2","x4_2","x5_2","x6_2","x7_2","x8_2","price_2")
print(sapply(db[, a2_cols], function(x) sum(x != 0)))
cat("\nSummary of price_2 and price_3:\n")
print(summary(db[, c("price_2","price_3")]))
